"""initial_clean

Revision ID: a4d8389b3228
Revises: 
Create Date: 2026-10-02 19:40:54.255984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d8389b3228'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('carbs_per_100g', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('carbs_per_100g >= 0 AND carbs_per_100g <= 100', name='check_carbs_range'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_foods_id'), 'foods', ['id'], unique=False)
    op.create_index(op.f('ix_foods_name'), 'foods', ['name'], unique=True)
    op.create_table('glucose_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('value > 0', name='check_glucose_value_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_glucose_events_id'), 'glucose_events', ['id'], unique=False)
    op.create_index(op.f('ix_glucose_events_occurred_at'), 'glucose_events', ['occurred_at'], unique=False)
    op.create_table('insulin_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('insulin_type', sa.String(length=10), nullable=False),
    sa.Column('dose', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("insulin_type IN ('short', 'long')", name='check_insulin_type'),
    sa.CheckConstraint('dose > 0', name='check_insulin_dose_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insulin_events_id'), 'insulin_events', ['id'], unique=False)
    op.create_index(op.f('ix_insulin_events_occurred_at'), 'insulin_events', ['occurred_at'], unique=False)
    op.create_table('meal_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=False),
    sa.Column('grams', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('carbs_grams', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('bread_units', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('bread_units >= 0', name='check_bread_units_positive'),
    sa.CheckConstraint('carbs_grams >= 0', name='check_carbs_grams_positive'),
    sa.CheckConstraint('grams > 0', name='check_grams_positive'),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meal_events_id'), 'meal_events', ['id'], unique=False)
    op.create_index(op.f('ix_meal_events_occurred_at'), 'meal_events', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_events_occurred_at'), table_name='meal_events')
    op.drop_index(op.f('ix_meal_events_id'), table_name='meal_events')
    op.drop_table('meal_events')
    op.drop_index(op.f('ix_insulin_events_occurred_at'), table_name='insulin_events')
    op.drop_index(op.f('ix_insulin_events_id'), table_name='insulin_events')
    op.drop_table('insulin_events')
    op.drop_index(op.f('ix_glucose_events_occurred_at'), table_name='glucose_events')
    op.drop_index(op.f('ix_glucose_events_id'), table_name='glucose_events')
    op.drop_table('glucose_events')
    op.drop_index(op.f('ix_foods_name'), table_name='foods')
    op.drop_index(op.f('ix_foods_id'), table_name='foods')
    op.drop_table('foods')
    # ### end Alembic commands ###
